### PR TITLE
add loongarch64 arch support

### PR DESCRIPTION
**Pull request by Godones**

### CODE REVIEW

**Comment by Evian-Zhang** [comment]
Thank you for your contribution! I wonder why the jump entries are designed to use absolute address instead of relative address? Does Loongarch Linux not support ASLR?

**Comment by Godones** [comment]
Loongarch Linux supports ASLR. When I use relative addresses in Rust's inline assembly, I find that the values ​​in jump entry are all 0, so I use absolute addresses instead.

**Comment by Evian-Zhang** [comment]
It's strange. Maybe an LLVM bug?

Anyway, using absolute addresses here is not suitable for applications with ASLR enabled, since those addresses may be relocated somewhere else at run time.

**Comment by Godones** [comment]
Maybe I can ask someone at loongarch.

**Comment by Godones** [comment]
The cross-rs tool currently uses the gnu toolchain for linking, but the version of binutils is low and does not support the relocation of R_LARCH_64_PCREL, so error occurs in calculating relative addresses. I can change the code to calculate relative addresses, but that might not pass the cross test.

**Comment by Evian-Zhang** [comment]
Is there any tracking issue for this problem at Rust main repository or cross-rs repo or anywhere else? I could track it and merge the PR after corresponding issue is solved.

**Comment by Godones** [comment]
Maybe this https://github.com/cross-rs/cross/pull/973

**Comment by heiher** [comment]
Thanks for your contribution to LoongArch. This is the tracking issue for this: https://github.com/cross-rs/cross/issues/1538

**Comment by Evian-Zhang** [comment]
It seems that the cross-rs has updated the binutils toolchain. Would you update your code for relative addresses? :)

**Comment by Evian-Zhang** [comment]
Thank you :)

**Pull request merged**
